module.exports = [
  'Abacate',
  'Abacaxi',
  'Abobrinha',
  'Abobrinhas',
  'Absinto',
  'Abóbora',
  'Abóbora moranga',
  'Abóbora-moranga',
  'Acelga',
  'Achocolatado',
  'Acém',
  'Adoçante',
  'Agrião',
  'Alcachofra',
  'Alcachofras',
  'Alcaparra',
  'Alcaparras',
  'Alcatra',
  'Alecrim',
  'Alface',
  'Alface romana',
  'Alfafa',
  'Alfavaca',
  'Alga',
  'Alga nori',
  'Algas',
  'Alho',
  'Alho poró',
  'Alho-poró',
  'Alhocenoura',
  'Alhos',
  'Aliche',
  'Almôndegas',
  'Amarula',
  'Ameixa',
  'Ameixa seca',
  'Ameixas',
  'Amendoim',
  'Amendoim torrado',
  'Amido',
  'Amido de batata',
  'Amido de milho',
  'Amora',
  'Amoras',
  'Amêndoas',
  'Anchova',
  'Angostura',
  'Anis estrelado',
  'Aratu',
  'Aroma de rum',
  'Arros',
  'Arroz',
  'Arroz 7 cereais',
  'Arroz arbóreo',
  'Arroz basmati',
  'Arroz integral',
  'Arroz koshihikari',
  'Arroz negra',
  'Arroz selvagem',
  'Arrroz',
  'Aspargo',
  'Aspargos',
  'Atum',
  'Aveia',
  'Aveia em flocos',
  'Avelã',
  'Avelãs',
  'Avestruz',
  'Azeite',
  'Azeite de dendê',
  'Azeite-de-dendê',
  'Azeitona',
  'Azeitonas',
  'Açafrão',
  'Açaí',
  'Açucar',
  'Açúcar',
  'Açúcar cristal',
  'Açúcar de confeiteiro',
  'Açúcar mascavo',
  'Bacalhau',
  'Bacon',
  'Bacon. farinha',
  'Badejo',
  'Baguete',
  'Baguetes',
  'Balsâmico',
  'Banana',
  'Banana prata',
  'Banana-da-terra',
  'Banana-nanica',
  'Banana-passa',
  'Bananada',
  'Bananas',
  'Bananas-da-terra',
  'Bananasn mangas',
  'Banha',
  'Barriga de porco',
  'Batata',
  'Batata baroa',
  'Batata bolinh',
  'Batata bolinha',
  'Batata palha',
  'Batata-doce',
  'Batata-palha',
  'Batatas',
  'Baunilha',
  'Bechamel',
  'Beringela',
  'Berinjela',
  'Berinjelas',
  'Beterraba',
  'Beterrabas',
  'Bicabornato de sódio',
  'Bicarbonato',
  'Bicarbonato de sódio',
  'Bife',
  'Biscoito',
  'Biscoito champanhe',
  'Biscoito maisena',
  'Biscoitos',
  'Bisocito champagne',
  'Bisteca de porco',
  'Bitter',
  'Bitter de chocolate',
  'Bittter',
  'Blueberries',
  'Blueberry',
  'Bochecha bovina',
  'Bolacha',
  'Bolacha champagne',
  'Bolinha de chocolate',
  'Bolonhesa',
  'Brandy',
  'Bresaola',
  'Brigadeiro',
  'Broas de milho',
  'Brocólis',
  'Broto',
  'Broto de feijão',
  'Broto de trevo',
  'Broto de trigo',
  'Brotos e erva',
  'Brown ale',
  'Brócolis',
  'Buquê garni',
  'Cabelo-de-anjo',
  'Cabeça de peixe',
  'Cabra',
  'Cabrito',
  'Cacau',
  'Cachaça',
  'Café',
  'Café solúvel',
  'Caju',
  'Calaras',
  'Calda de camarão',
  'Calda de chocolate',
  'Calda light de morango',
  'Caldo',
  'Caldo de camarão',
  'Caldo de carne',
  'Caldo de frango',
  'Caldo de galinha',
  'Caldo de legumes',
  'Caldo de peixe',
  'Camarão',
  'Camarão seco',
  'Camarões',
  'Camarões secos',
  'Camomila',
  'Canela',
  'Canela em pó',
  'Canjica',
  'Canjiquinha',
  'Capim cidreira',
  'Capim santo',
  'Capim-cidreira',
  'Capim-limão',
  'Capim-santo',
  'Caraambolas',
  'Carambola',
  'Carambolas',
  'Caramelo',
  'Carapau',
  'Cardamomo',
  'Carne',
  'Carne assada',
  'Carne de porco',
  'Carne de siri',
  'Carne magra',
  'Carne moída',
  'Carne seca',
  'Carne-seca',
  'Carneiro',
  'Carnes',
  'Carolinas',
  'Carpaccio',
  'Carvo-da-índia',
  'Cará',
  'Casatanha de caju',
  'Casca de banana',
  'Casca de laranja',
  'Casca de melancia',
  'Castanha',
  'Castanha de caju',
  'Castanha de cajú',
  'Castanha do Pará',
  'Castanha-de-caju',
  'Castanha-do-Pará',
  'Castanha-do-pará',
  'Castanhas',
  'Catalônia',
  'Catchup',
  'Catupiry',
  'Cavaquinhas',
  'Cação',
  'Cebol-pérola',
  'Cebola',
  'Cebola alho-poró',
  'Cebola roxa',
  'Cebola-pérola',
  'Cebolas',
  'Cebolina',
  'Cebolinha',
  'Cebolinha verde',
  'Cebolinha-verde',
  'Cebolinhas',
  'Cenoura',
  'Cenouras',
  'Centeio',
  'Cerefólio',
  'Cereja',
  'Cerejas',
  'Cerejas. cebola',
  'Cerveja',
  'Cerveja escura',
  'Cevada',
  'Cevadinha',
  'Chalotas',
  'Champanhe',
  'Champignon',
  'Champignons',
  'Chantilly',
  'Charque',
  'Cheddar',
  'Cheiro verde',
  'Cheiro-verde',
  'Chicória',
  'Chili',
  'Chilli',
  'Chocolate',
  'Chocolate ao leite light',
  'Chocolate branco',
  'Chocolate em pó',
  'Chocolate granulado',
  'Chope preto',
  'Chuchu',
  'Chucrute',
  'Chutney de manga',
  'Chá de camomila',
  'Chá mate',
  'Chá verde',
  'Ciboulette',
  'Citronela',
  'Clara de ovo',
  'Claras',
  'Claras de ovo',
  'Club soda',
  'Coalhada',
  'Coalhada seca',
  'Cobertura light sabor chocolate',
  'Coca-cola',
  'Coco',
  'Coco desidratado',
  'Cocos',
  'Codorna',
  'Coelho',
  'Coentro',
  'Cogumelo',
  'Cogumelo erinji',
  'Cogumelos',
  'Colorau',
  'Cominho',
  'Conhaque',
  'Contrafilé',
  'Cookies de chocolate',
  'Copa lombo',
  'Corante',
  'Corante caramelo',
  'Cordeiro',
  'Corn flakes',
  'Corvina',
  'Costela de boi',
  'Costela de porco',
  'Costelinha',
  'Cottage',
  'Couce',
  'Couscous',
  'Couve',
  'Couve-flor',
  'Couve-manteiga',
  'Coxa',
  'Coxa de peru',
  'Coxas',
  'Coxinhas de frango',
  'Coxão duro',
  'Coxão mole',
  'Cravo',
  'Cravo-da-Índia',
  'Cravo-da-índia',
  'Cravos',
  'Cravos-da-índia',
  'Cream cheese',
  'Cream cheese light',
  'Cream chesse',
  'Creme',
  'Creme azedo',
  'Creme de leite',
  'Creme de leite light',
  'Creme de lete',
  'Creme fresco',
  'Creme vegetal light',
  'Cremor',
  'Crouton',
  'Croutons',
  'Croûton',
  'Cupim',
  'Cupuaçu',
  'Curry',
  'Cuscuz',
  'Cúrcuma',
  'Damasco',
  'Damasco seco',
  'Damascos',
  'Demi glacê',
  'Demi-glacê',
  'Dente-de-leão',
  'Dill',
  'Doce de abóbora diet',
  'Doce de goiaba',
  'Doce de leite',
  'Endro',
  'Endívias',
  'Erva doce',
  'Erva-cidreira',
  'Erva-doce',
  'Erva-mate',
  'Ervas',
  'Ervas frescas',
  'Ervilha',
  'Ervilha fresca',
  'Ervilha torta',
  'Ervilha-torta',
  'Ervilhas',
  'Escalope',
  'Escalopinhos',
  'Escargots',
  'Escarola',
  'Espaguete',
  'Especiarias',
  'Espetinho',
  'Espeto',
  'Espinafre',
  'Espumante',
  'Essência',
  'Essência de amêndoa',
  'Essência de baunilha',
  'Estragão',
  'Extrato de tomate',
  'Fanta',
  'Faondant',
  'Farelo de aveia',
  'Farelo de trigo',
  'Farfale',
  'Farinha',
  'Farinha de amêndoas',
  'Farinha de aveia',
  'Farinha de castanha de caju',
  'Farinha de mandioca',
  'Farinha de mandioca crua',
  'Farinha de mandioca flocada',
  'Farinha de milho',
  'Farinha de piracuí',
  'Farinha de rosca',
  'Farinha de semolina',
  'Farinha de trigo',
  'Farinha de trigo integral',
  'Farinha de trigo. fermento',
  'Farinha dÁgua',
  'Farinha integral',
  'Farinha láctea',
  'Farinha provençal',
  'Farofa',
  'Fava',
  'Fava de baunilha',
  'Favas',
  'Feijão',
  'Feijão branco',
  'Feijão preto',
  'Feijão-branco',
  'Fermento',
  'Fermento biológico',
  'Fermento em pó',
  'Fettuccine',
  'Fetuccine',
  'Figo',
  'Figos',
  'Filé',
  'Filé de frango',
  'Filé de pescada',
  'Filé de sororoca',
  'Filé mignon',
  'Filé-mignon',
  'Flakes',
  'Flocos de milho',
  'Flor de laranjeira',
  'Flor de sal',
  'Folha de laranjeira',
  'Folhas',
  'Folhas de bananeira',
  'Folhas de hortelã',
  'Folhas verdes',
  'Fondant',
  'Fondue',
  'Fraldinha',
  'Framboesa',
  'Framboesas',
  'Frango',
  'Frinha de trigo',
  'Frozen iogurte',
  'Fruta',
  'Fruta cristalizada',
  'Frutas',
  'Frutas secas',
  'Frutas vermelhas',
  'Frutos do mar',
  'Fubá',
  'Fubá amarelo',
  'Funcho',
  'Fundo claro de ave',
  'Funghi',
  'Fusili',
  'Fusilli',
  'Fécula de batata',
  'Fígado',
  'Fígado de pato',
  'Galangal',
  'Galeto',
  'Galinha',
  'Galo',
  'Ganache',
  'Garam masala',
  'Gelado',
  'Gelatina',
  'Gelatina em pó',
  'Geleia',
  'Geleia de amora',
  'Geleia de manga',
  'Geleia de maracujá',
  'Gelo',
  'Geléia',
  'Gema',
  'Gema de ovo',
  'Gemas',
  'Gengibre',
  'Gergelim',
  'Germe de trigo',
  'Gim',
  'Glaçúcar',
  'Glicose',
  'Glucose',
  'Glucose de milho',
  'Goiaba',
  'Goiabada',
  'Goma',
  'Goma de tapioca',
  'Gordura vegetal',
  'Gorgonzola',
  'Grana padano',
  'Granola',
  'Grapa',
  'Grapefruit',
  'Graviola',
  'Groselha',
  'Gruyère',
  'Gruyére',
  'Grão-de-bico',
  'Grãos de trigo integral',
  'Guaraná',
  'Guinness',
  'Hambúrguer',
  'Hibisco',
  'Hondashi',
  'Hortelã',
  'Inhame',
  'Iogurte',
  'Irish cream',
  'Jalapeño',
  'Jambo',
  'Jambu',
  'Jerimum',
  'Joelho de porco',
  'Kani kama',
  'Kasseler',
  'Katsuoboshi',
  'Ketchup',
  'Kiwi',
  'Kiwis',
  'Kummel',
  'Lagarto',
  'Lagosta',
  'Lagostins',
  'Laranja',
  'Laranja-lima',
  'Laranjas',
  'Lasanha',
  'Legumes',
  'Legumes em conserva',
  'Leite',
  'Leite baixa lactose',
  'Leite com baixa lactose',
  'Leite condensado',
  'Leite condensado de soja',
  'Leite condensado light',
  'Leite consensado',
  'Leite de coco',
  'Leite de soja',
  'Leite em pó',
  'Leite em pó de soja',
  'Leite integral',
  'Lentilha',
  'Lentilhas',
  'Lichia',
  'Licor',
  'Licor de  amêndoas',
  'Licor de amaretto',
  'Licor de cassis',
  'Licor de framboesa',
  'Lima da pérsia',
  'Limonada',
  'Limão',
  'Limão siciliano',
  'Linguado',
  'Linguine',
  'Linguiça',
  'Linguiça portuguesa',
  'Linhaça',
  'Lombo',
  'Lombo de avestruz',
  'Lombo de coelho',
  'Lombo de porco',
  'Louro',
  'Lula',
  'Lulas',
  'Língua',
  'Macarrão',
  'Macarrão de arroz',
  'Macarrão gravatinha',
  'Macarrão instantâneo',
  'Macarrão linguine',
  'Macarrão para yakisoba',
  'Macarrão rigatoni',
  'Macis',
  'Maionese',
  'Maionese light',
  'Maisena',
  'Majericão',
  'Mamão',
  'Mamão papaia',
  'Mamões',
  'Mandioca',
  'Mandioca cozida',
  'Mandioquinha',
  'Manga',
  'Mangas',
  'Manjericão',
  'Manjerona',
  'Manteiga',
  'Manteiga clarificada',
  'Manteiga de amendoim',
  'Manteiga de garrafa',
  'Manteiga. gemas',
  'Mantiga',
  'Maracujá',
  'Margarina',
  'Margarina light',
  'Mariscos',
  'Marsala',
  'Marshmallow',
  'Mascarpone',
  'Massa',
  'Massa curta',
  'Massa de guioza',
  'Massa de pastel',
  'Massa de pizza',
  'Massa fillo',
  'Massa filo',
  'Massa folhada',
  'Massa para lasanha',
  'Massa para torta',
  'Massa seca',
  'Maçã',
  'Maçã desidratada',
  'Maçã fuji',
  'Maçã verde',
  'Maçãs',
  'Meia cura',
  'Mel',
  'Melado',
  'Melado de romã',
  'Melaço',
  'Melão',
  'Menta',
  'Merluzza',
  'Mexerica',
  'Mexilhões',
  'Milho',
  'Milho branco',
  'Milho verde',
  'Milho-verde',
  'Mini-abóboras',
  'Miniagrião',
  'Minicenoura',
  'Minimilho',
  'Minirabanete',
  'Minirrúcula',
  'Minirúcula',
  'Minitender',
  'Miojo',
  'Mirtilo',
  'Mirtilos',
  'Missô',
  'Mocotó',
  'Mole poblano',
  'Molho',
  'Molho barbecue',
  'Molho bechamel',
  'Molho branco',
  'Molho de carne',
  'Molho de mostarda',
  'Molho de peixe',
  'Molho de soja',
  'Molho de tomate',
  'Molho inglês',
  'Molho pesto',
  'Molho sú',
  'Molho tarê',
  'Moranga',
  'Morango',
  'Morangos',
  'Mortadela',
  'Mostarda',
  'Mostarda de dijon',
  'Mostarda dijon',
  'Moyashi',
  'Muffins',
  'Mussarela',
  'Mussarela de búfala',
  'Músculo',
  'Nabo',
  'Namorado',
  'Nata',
  'Natas',
  'Nhoque',
  'Nirá',
  'Noz moscada',
  'Noz-moscada',
  'Nozes',
  'Nozes pecãs',
  'Nutella',
  'Ora-pró-nóbis',
  'Oregáno',
  'Orégano',
  'Ossobuco',
  'Ostras',
  'Ovo',
  'Ovomaltine',
  'Ovos',
  'Ovos de codorna',
  'Pacu',
  'Paio',
  'Paleta de cordeiro',
  'Palitos',
  'Palmito',
  'Palmito pupunha',
  'Pancetta',
  'Panetone',
  'Pappardelle',
  'Pargo',
  'Parmesão',
  'Passas',
  'Passata de tomate',
  'Pasta',
  'Pasta de curry',
  'Pasta de damasco',
  'Patinho',
  'Pato',
  'Paçoca',
  'Paçocas',
  'Paõ',
  'Pecorino',
  'Pecã',
  'Peito de frango',
  'Peito de peru',
  'Peito de peru defumado',
  'Peixe',
  'Penne',
  'Pepino',
  'Pepino japonês',
  'Pepinos',
  'Pequi',
  'Pera',
  'Pera seca',
  'Peras',
  'Pernil',
  'Pernil de porco',
  'Peru',
  'Peru defumado',
  'Physalis',
  'Picanha',
  'Picles',
  'Pimenta',
  'Pimenta caiena',
  'Pimenta calabresa',
  'Pimenta cambuci',
  'Pimenta da Jamaica',
  'Pimenta da jamaica',
  'Pimenta dedo-de-moça',
  'Pimenta jalapeno',
  'Pimenta malagueta',
  'Pimenta rosa',
  'Pimenta síria',
  'Pimenta vermelha',
  'Pimenta-da-jamaica',
  'Pimenta-de-cheiro',
  'Pimenta-do-reino',
  'Pimenta-malagueta',
  'Pimenta-síria',
  'Pimentão',
  'Pimentão vermelho',
  'Pinole',
  'Pinoli',
  'Pintado',
  'Pipoca',
  'Pirarucu',
  'Pirão',
  'Pisco',
  'Pistache',
  'Pitta',
  'Polenta',
  'Polenta instantânea',
  'Polpa de castanha',
  'Polpa de frutas',
  'Polpa de tomate',
  'Polvilho',
  'Polvilho azedo',
  'Polvilho doce',
  'Polvilho-doce',
  'Polvo',
  'Porcini',
  'Presuntada',
  'Presunto',
  'Presunto cru',
  'Presunto defumado de peru',
  'Provolone',
  'Pupunha',
  'Purê',
  'Páprica',
  'Páprica doce',
  'Páprica picante',
  'Pães',
  'Pãezinhos',
  'Pão',
  'Pão amanhecido',
  'Pão de folha árabe',
  'Pão de forma',
  'Pão de fôrma',
  'Pão de miga',
  'Pão francês',
  'Pão integral',
  'Pão italiano',
  'Pão pita',
  'Pão português',
  'Pão sírio',
  'Pêssego',
  'Pó para pudim light',
  'Queijo',
  'Queijo Minas',
  'Queijo Serra da Canastra',
  'Queijo brie',
  'Queijo coalho',
  'Queijo cottage',
  'Queijo de cabra',
  'Queijo feta',
  'Queijo grana padano',
  'Queijo gruyère',
  'Queijo meia-cura',
  'Queijo minas',
  'Queijo minas curado',
  'Queijo mussarela',
  'Queijo parmesão',
  'Queijo pecorino',
  'Queijo prato',
  'Queijo roquefort',
  'Queijo-de-minas',
  'Quiabo',
  'Quiabos',
  'Quinoa',
  'Rabada',
  'Rabanadas',
  'Rabanete',
  'Rabo de boi',
  'Radicchio',
  'Radichio',
  'Ragu',
  'Raiz forte',
  'Ravioli',
  'Refrigerante',
  'Refrigerante de laranja',
  'Repolho',
  'Requeijão',
  'Ricota',
  'Robalo',
  'Romate',
  'Rosbife',
  'Rum',
  'Rúcula',
  'Sagu',
  'Sakê',
  'Sal',
  'Sal com ervas',
  'Sal grosso',
  'Salmão',
  'Salmão defumado',
  'Salsa',
  'Salsicha',
  'Salsichas',
  'Salsinha',
  'Salsão',
  'Saquê',
  'Saquê seco',
  'Sardinha',
  'Sardinhas',
  'Segurelha',
  'Semente de abóbora',
  'Semente de coentro',
  'Semente de gergelim',
  'Semente de girassol',
  'Semente de linhaça',
  'Semente de mostarda',
  'Sementes',
  'Sementes de coentro',
  'Sementes de girassol',
  'Sementes de papoula',
  'Semolina',
  'Sete grãos',
  'Shimeji',
  'Shitake',
  'Shitake seco',
  'Shoyu',
  'Siri',
  'Snoubar',
  'Sobrecoxa',
  'Soda',
  'Soja',
  'Sorbet',
  'Sorvete',
  'Sorvete de creme',
  'Sorvete de morango',
  'Sorvetem leite condensado',
  'Spaguettini',
  'Suco',
  'Suco de laranja',
  'Suco de larranja',
  'Suco de maçã',
  'Sucrilhos',
  'Supreme',
  'Surubim',
  'Suspiro',
  'Suspiros',
  'Suã',
  'Sálvia',
  'Tabasco',
  'Tagliarini',
  'Tainha',
  'Talharim',
  'Talos de espinafre',
  'Talos de rúcula',
  'Tamboril',
  'Tangerinas',
  'Tapioca',
  'Tequila',
  'Tilápia',
  'Tofu',
  'Tomate',
  'Tomate cereja',
  'Tomate seco',
  'Tomate-cereja',
  'Tomate. vinho branco',
  'Tomates',
  'Tomilho',
  'Tomilho-limão',
  'Tortilla',
  'Toucinho',
  'Trenette',
  'Trigo',
  'Trigo em grão',
  'Truta',
  'Truta defumada',
  'Umburana',
  'Uva',
  'Uva passa',
  'Uva passas',
  'Uva-passa',
  'Uva-passa branca',
  'Uva-passas',
  'Uvas',
  'Uvas verdes',
  'Uísque',
  'Vagem',
  'Vagens',
  'Vanilina',
  'Vatapá',
  'Veinho',
  'Vermelho',
  'Vermute',
  'Vieiras',
  'Vinagre',
  'Vinagre balsâmico',
  'Vinagre de arroz',
  'Vinagre de maçã',
  'Vinagre de vinho branco',
  'Vinagre de vinho tinto',
  'Vinagrete',
  'Vinho',
  'Vinho Madeira seco',
  'Vinho branco',
  'Vinho do Porto',
  'Vinho do porto',
  'Vinho madeira',
  'Vinho tinto',
  'Vinto branco',
  'Vodca',
  'Vângoles',
  'Vôngoles',
  'Waldorf',
  'Wasabi',
  'Wassabi',
  'Wrap',
  'Xarope',
  'Xerez',
  'Zaathar',
  'Água',
  'Água com gás',
  'Água de coco',
  'Água mineral',
  'Óleo',
  'Óleo de canola',
  'Óleo de gergelim',
  'Óleo de girassol',
  'Óleo de milho',
  'Óleo de soja',
  'Óleo vegetal',
];
